name: iac-dev

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/env/dev/**'
  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action to run"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform_dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/env/dev   # 👈 FIXED path

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan (for apply)
        if: github.event.inputs.action == 'apply' || github.event_name == 'push'
        run: terraform plan -var-file=dev.tfvars -no-color -input=false -out planfile

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply' || github.event_name == 'push'
        run: terraform apply -auto-approve -input=false planfile

      - name: Terraform Destroy Plan (Preview)
        if: github.event.inputs.action == 'destroy'
        run: terraform plan -destroy -var-file=dev.tfvars -no-color -input=false -out destroy.tfplan

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform apply -auto-approve destroy.tfplan
