name: iac-dev

on:
  push:
  workflow_dispatch:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  terraform_dev:
    runs-on: ubuntu-latest
    defaults:
      defaults:
       run:
         shell: bash
         working-directory: ./terraform 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.3.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secret.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -var-file=dev.tfvars -out planfile

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure' 
        run: exit 1
      
      - name: Terraform Apply
        id: apply 
        if: ${{ steps.plan.outcome == 'success' }}
        run: terraform apply -no-color -input=false -var-file=dev.tfvars -parallelism=1 planfile
        