name: iac-dev

on:
  push:
    branches:
      - main
    paths:
      - terraform/**

  workflow_dispatch:
    inputs:
      action:
        description: "Choose Terraform action to run"
        required: true
        default: apply
        type: choice
        options:
          # - plan
          - apply
          - destroy


jobs:
  terraform_dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      # Runs always to show plan
      - name: Terraform Plan
        if: github.event_name == 'push' || github.event.inputs.action == 'plan'
        run: terraform plan -no-color -input=false -var-file=dev.tfvars -out planfile

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        run: terraform apply -no-color -input=false -var-file=dev.tfvars -parallelism=1 planfile

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -no-color -input=false -var-file=dev.tfvars
